version: '3.8'

services:
  smtp-server:
    build: .
    ports:
      - "2525:2525"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - GPT4_TASK=${GPT4_TASK}
    volumes:
      - ./smtp_server.py:/app/smtp_server.py
    restart: unless-stopped
