version: '3.8'

services:
  smtp-server:
    build: .
    ports:
      - "2525:2525"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - GPT4_TASK=${GPT4_TASK}
      - PAGERDUTY_FROM_EMAIL=${PAGERDUTY_FROM_EMAIL}
      - PAGERDUTY_API_TOKEN=${PAGERDUTY_API_TOKEN}
      - PAGERDUTY_SERVICE_ID=${PAGERDUTY_SERVICE_ID}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
    volumes:
      - ./smtp_server.py:/app/smtp_server.py
    restart: unless-stopped
